mainprog main;
int[10] x3, y1;
float a, b, c, a1;

function der456(hello:int;world:float;perfect:int) : float;
	float[100] x;
	begin
		x[0]=3.12;
		if perfect > 1:
			begin
				abc123(123123,1.0);
				return 0
			end
		elif perfect == 2:
			begin
				abc123(123123,1.0);
				return 1
			end
	end

procedure abc123 (hello:int;world:float);
	int[10] x;
	begin
		a=.3
	end

begin
	print(abc123(123*x3[x3[y1]],-1384));
	for y1 in x3:
	begin
		if a > 13241.0:
			begin
				abc123(123123,1.0)
			end
		elif a == 0:
			begin
				while 1!=2:
					begin
				        abc123(123123,1.0)
					end
			end

		else:
			begin
				  abc123(123123,1.0)
			end
	end
	else:
	    begin
	        print(a)
	    end
end
